version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
    environment:
      REDIS_CONNECTION_STRING: redis://redis:6379
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
